local _, FSB = ...

-- English texts. Missing keys fall back to French (see frFR.lua).
FSB.Locales = FSB.Locales or {}
FSB.Locales.enUS = {
    ADDON_LOADED   = "Forever Stuff Book loaded. Type /fsb for help.",
    ANALYSIS_TITLE = "FSB",
    PROFILE        = "Profile",
    SPEC           = "Role",
    LABEL_SPEC     = "Spec",
    LABEL_CLASS    = "Class",
    ENABLED        = "FSB enabled",
    DISABLED       = "FSB disabled",

    VERDICT_TAKE         = "TAKE IT",
    VERDICT_BETTER_OTHER = "BETTER FOR SOMEONE ELSE",
    VERDICT_CUPI         = "PASS",
    UNUSABLE        = "Your character cannot use this",
    REQ_LEVEL       = "Requires level %d",
    BETTER_FOR      = "More useful to: %s",
    UNSCANNED       = "%d member(s) not analyzed yet",
    SET_GAINED      = "Set bonus gained: %d tier(s)",
    SET_LOST        = "Set bonus lost: %d tier(s)",
    SET_PARTIAL     = "Partial analysis: set tiers unreadable",
    SET_UNVALUED    = "(not counted in the verdict)",
    VERDICT_UNKNOWN = "ANALYSIS IMPOSSIBLE",
    UNKNOWN_STATS   = "Unrecognized stats: unreliable analysis (/fsb inconnus)",
    VERDICT_EQUIP   = "EQUIP",
    VERDICT_OFFSPEC = "OFF-SPEC",
    VERDICT_SELL    = "SELL / DISENCHANT",

    HELP = {
        "/fsb: open the settings",
        "/fsb on | off: enable or disable the analysis",
        "/fsb lang fr | en: change the language",
        "/fsb role: choose the role you play with the current spec",
        "/fsb rapport: the WHOLE diagnostic at once (state, probe, unknown stats, log, last item, specs, weights) to copy",
        "/fsb etat: diagnostics (mode, scan, spec)",
        "/fsb poids: indicative weights of all profiles (not editable)",
        "/fsb log [vider|off|on]: hesitation log (send it for the update)",
        "/fsb mauvais [text]: flag a wrong verdict on the last hovered item",
        "/fsb specs: list the specializations of every class (diagnostics)",
        "/fsb debug: details of the last hovered item's analysis",
        "/fsb sonde: check the APIs in game (read-only)",
        "/fsb inconnus: stats seen and not recognized",
    },
    PROFILE_ACTIVE  = "Active profile: %s",
    PROFILE_UNKNOWN = "Profile not found: %s",
    NO_UNKNOWN      = "No unrecognized stat encountered.",
    STATE           = "Mode: %s | members to scan: %d | comparable members: %d",
    STATE_SPEC      = "Spec: %s | profile: %s",

    UI_TITLE        = "Forever Stuff Book",
    UI_ENABLED      = "Analysis enabled",
    UI_WEIGHTS      = "Stat weights (fixed, indicative)",
    LOG_CLEARED     = "Log cleared.",
    LOG_OFF         = "Hesitation log disabled.",
    LOG_ON          = "Hesitation log enabled.",
    LOG_NOITEM      = "Hover an item first, then /fsb mauvais [comment].",
    LOG_FLAGGED     = "Noted in the log. Thanks: /fsb log to export it.",
    LOG_COUNT       = "Log: %d entr(ies) (/fsb log)",
    COPY_TITLE      = "Forever Stuff Book — Ctrl+A then Ctrl+C to copy",
    UI_ICONS        = "Icons",
    UI_DETAILS      = "Details",
    UI_STATUS       = "%s",
    UI_PICK_ROLE    = "My role",
    ROLE_PICK_TITLE = "What do you play with %s?",
    ROLE_PICK_NOTE  = "Saved for this spec (/fsb role to change).",
    ROLE_PICK_BTN   = "My role",
    UI_TAB_HOME     = "Home",
    UI_TAB_SETTINGS = "Settings",
    HOME_TAGLINE    = "Gear and loot assistant",
    HOME_DESC       = "Hover an equippable item: FSB compares its value to your real setup (rings, trinkets, weapons, set bonuses) and shows a clear verdict in the tooltip. In a group, it also spots items that suit another member better.",
    HOME_V1         = "EQUIP · TAKE IT",
    HOME_V1_DESC    = "A real upgrade for your role.",
    HOME_V2         = "OFF-SPEC",
    HOME_V2_DESC    = "Useful for another role of your class.",
    HOME_V3         = "BETTER FOR SOMEONE ELSE",
    HOME_V3_DESC    = "In a dungeon or raid: another member will benefit more.",
    HOME_V4         = "SELL · DISENCHANT · PASS",
    HOME_V4_DESC    = "Not useful to you.",
    HOME_NOTE       = "100% passive: FSB never acts for you, you always decide. Your role follows your talents; a question is asked only when in doubt.",
    HOME_CREDITS    = "Developed by Koga / Fitaxal",
    UI_TAB_DEV      = "Commands",
    DEV_OPEN        = "100% open source project (MIT license): code, tests and documentation at github.com/tomvieilledent/AddOn_FSB_wow. To modify or propose an improvement, read CONTRIBUTING.md and run the tests with \"sh tests/run_all.sh\". To report a problem: /fsb rapport then paste the result.",
    DEV_COMMANDS    = "Commands",
    UI_SECTION_CHAR = "Character",
    UI_SECTION_DISPLAY = "Display",
    UI_TAB_GENERAL  = "Settings",
    UI_TAB_STATS    = "Stats",
    UI_LANGUAGE     = "Language",
    UI_STATS_NOTE   = "Temporary tab: active profile weights, until the final balance.",
    UI_ALL_PROFILES = "All profiles (copy)",
    LANG_CHANGED    = "Language: English",
    LANG_UNKNOWN    = "Unknown language: %s (fr or en)",
    POIDS_TITLE     = "%s (fixed, indicative weights)",
    TREE_NAMES = {
        WARRIOR = { "Arms", "Fury", "Protection" }, PALADIN = { "Holy", "Protection", "Retribution" },
        HUNTER = { "Beast Mastery", "Marksmanship", "Survival" }, ROGUE = { "Assassination", "Combat", "Subtlety" },
        PRIEST = { "Discipline", "Holy", "Shadow" }, SHAMAN = { "Elemental", "Enhancement", "Restoration" },
        MAGE = { "Arcane", "Fire", "Frost" }, WARLOCK = { "Affliction", "Demonology", "Destruction" },
        DRUID = { "Balance", "Feral", "Restoration" },
    },
    STATS = {
        RESISTANCE0_NAME = "Armor", ITEM_MOD_DAMAGE_PER_SECOND_SHORT = "Weapon DPS",
        ITEM_MOD_STRENGTH_SHORT = "Strength", ITEM_MOD_AGILITY_SHORT = "Agility", ITEM_MOD_STAMINA_SHORT = "Stamina",
        ITEM_MOD_INTELLECT_SHORT = "Intellect", ITEM_MOD_SPIRIT_SHORT = "Spirit",
        ITEM_MOD_ATTACK_POWER_SHORT = "Attack power", ITEM_MOD_SPELL_POWER_SHORT = "Spell power",
        ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = "Damage power", ITEM_MOD_SHADOW_DAMAGE_DONE_SHORT = "Shadow damage",
        ITEM_MOD_FIRE_DAMAGE_DONE_SHORT = "Fire damage", ITEM_MOD_FROST_DAMAGE_DONE_SHORT = "Frost damage",
        ITEM_MOD_NATURE_DAMAGE_DONE_SHORT = "Nature damage", ITEM_MOD_ARCANE_DAMAGE_DONE_SHORT = "Arcane damage",
        ITEM_MOD_HOLY_DAMAGE_DONE_SHORT = "Holy damage", ITEM_MOD_SPELL_HEALING_DONE_SHORT = "Healing power",
        ITEM_MOD_MANA_REGENERATION_SHORT = "MP5", ITEM_MOD_CRIT_RATING_SHORT = "Critical strike",
        ITEM_MOD_HIT_RATING_SHORT = "Hit", ITEM_MOD_HASTE_RATING_SHORT = "Haste",
        ITEM_MOD_EXPERTISE_RATING_SHORT = "Expertise", ITEM_MOD_MASTERY_RATING_SHORT = "Mastery",
        ITEM_MOD_DEFENSE_SKILL_RATING_SHORT = "Defense", ITEM_MOD_DODGE_RATING_SHORT = "Dodge",
        ITEM_MOD_PARRY_RATING_SHORT = "Parry", ITEM_MOD_BLOCK_RATING_SHORT = "Block",
        ITEM_MOD_RESILIENCE_RATING_SHORT = "Resilience",
    },
    PROFILES = {
        ["Soigneur"] = "Healer", ["Dégâts magiques"] = "Magic damage", ["Dégâts physiques"] = "Physical damage",
        ["Tank"] = "Tank", ["Dégâts Ombre"] = "Shadow damage", ["Dégâts Feu"] = "Fire damage",
        ["Dégâts Givre"] = "Frost damage", ["Dégâts Nature"] = "Nature damage", ["Dégâts Arcanes"] = "Arcane damage",
        ["Dégâts Sacré"] = "Holy damage",
    },
}
