local _, FSB = ...

-- Table de textes. Une autre langue = un autre fichier qui remplit FSB.L.
FSB.L = {
    ADDON_LOADED   = "Forever Stuff Book chargé. Tape /fsb pour l'aide.",
    ANALYSIS_TITLE = "FSB",
    PROFILE        = "Profil",
    ENABLED        = "FSB activé",
    DISABLED       = "FSB désactivé",

    VERDICT_TAKE         = "À PRENDRE",
    VERDICT_BETTER_OTHER = "MEILLEUR POUR UN AUTRE",
    VERDICT_CUPI         = "CUPI",
    UNUSABLE        = "Non utilisable par ton personnage",
    REQ_LEVEL       = "Niveau %d requis",
    BETTER_FOR      = "Plus utile à : %s",
    UNSCANNED       = "%d membre(s) pas encore analysé(s)",
    SET_GAINED      = "Bonus de set gagné : %d palier(s)",
    SET_LOST        = "Bonus de set perdu : %d palier(s)",
    SET_PARTIAL     = "Analyse partielle : paliers de set non lisibles",
    SET_UNVALUED    = "(non chiffré dans le verdict)",
    VERDICT_UNKNOWN = "ANALYSE IMPOSSIBLE",
    UNKNOWN_STATS   = "Stats non reconnues : analyse peu fiable (/fsb inconnus)",
    VERDICT_EQUIP   = "À ÉQUIPER",
    VERDICT_OFFSPEC = "OFF-SPÉ",
    VERDICT_SELL    = "VENDRE / DÉSENCHANTER",

    HELP = {
        "/fsb : ouvre la configuration",
        "/fsb on | off : active ou désactive l'analyse",
        "/fsb role : choisir le rôle joué avec la spé actuelle",
        "/fsb set [<valeur>] : valeur d'un palier de bonus de set (profil actif, 0 = non estimé)",
        "/fsb etat : diagnostic (mode, scan, spé)",
        "/fsb profils : liste les profils",
        "/fsb nouveau <nom> : crée un profil (copie du profil actif)",
        "/fsb supprimer <nom> : supprime un profil",
        "/fsb poids [<stat> <valeur>] : affiche ou modifie les poids du profil actif",
        "/fsb log [vider|off|on] : journal des hésitations (à envoyer pour la mise à jour)",
        "/fsb mauvais [texte] : signale un mauvais verdict sur le dernier objet survolé",
        "/fsb specs : liste les spécialisations de toutes les classes (diagnostic)",
        "/fsb debug : détail de l'analyse du dernier objet survolé",
        "/fsb sonde : vérifie les API en jeu (lecture seule)",
        "/fsb inconnus : stats rencontrées et non reconnues",
    },
    PROFILE_ACTIVE  = "Profil actif : %s",
    PROFILE_UNKNOWN = "Profil introuvable : %s",
    PROFILE_CREATED = "Profil créé : %s",
    PROFILE_EXISTS  = "Nom invalide ou déjà utilisé : %s",
    PROFILE_DELETED = "Profil supprimé : %s",
    PROFILE_KEEP_ONE = "Impossible de supprimer ce profil.",
    WEIGHT_SET      = "%s = %s (profil %s)",
    STAT_UNKNOWN    = "Stat inconnue : %s (alias : voir /fsb poids)",
    NO_UNKNOWN      = "Aucune stat inconnue rencontrée.",
    SET_VALUE       = "Valeur d'un palier de set : %s (profil %s)",
    STATE           = "Mode : %s | membres à scanner : %d | membres comparables : %d",
    STATE_SPEC      = "Spé : %s | profil : %s",

    -- Interface
    UI_TITLE        = "Forever Stuff Book",
    UI_ENABLED      = "Analyse activée",
    UI_PROFILES     = "Profils",
    UI_NEW          = "Créer",
    UI_DELETE       = "Supprimer",
    UI_WEIGHTS      = "Poids des statistiques (profil actif)",
    UI_THRESHOLDS   = "Seuils (%)",
    UI_UPGRADE      = "Upgrade min.",
    UI_MARGIN       = "Marge « autre »",
    UI_SETVALUE     = "Valeur palier de set",
    LOG_CLEARED     = "Journal vidé.",
    LOG_OFF         = "Journal des hésitations désactivé.",
    LOG_ON          = "Journal des hésitations activé.",
    LOG_NOITEM      = "Survole d'abord un objet, puis /fsb mauvais [commentaire].",
    LOG_FLAGGED     = "Noté dans le journal. Merci : /fsb log pour l'exporter.",
    LOG_COUNT       = "Journal : %d entrée(s) (/fsb log)",
    COPY_TITLE      = "Forever Stuff Book — Ctrl+A puis Ctrl+C pour copier",
    UI_ICONS        = "Icônes",
    UI_DETAILS      = "Détails",
    UI_STATUS       = "Spé détectée : %s  ·  profil actif : %s",
    UI_PICK_ROLE    = "Mon rôle",
    ROLE_PICK_TITLE = "Que joues-tu avec %s ?",
    ROLE_PICK_NOTE  = "Mémorisé pour cette spé (/fsb role pour changer).",
    ROLE_PICK_BTN   = "Mon rôle",
}
