local _, FSB = ...

-- Table de textes. Une autre langue = un autre fichier qui remplit FSB.L.
FSB.L = {
    ADDON_LOADED   = "Forever Stuff Book chargé. Tape /fsb pour l'aide.",
    ANALYSIS_TITLE = "Analyse FSB",
    PROFILE        = "Profil",
    ENABLED        = "FSB activé",
    DISABLED       = "FSB désactivé",

    VERDICT_TAKE         = "À PRENDRE",
    VERDICT_BETTER_OTHER = "MEILLEUR POUR UN AUTRE",
    VERDICT_CUPI         = "CUPI",
    UNUSABLE        = "Non utilisable par ton personnage",
    REQ_LEVEL       = "Niveau %d requis",
    BETTER_FOR      = "Plus utile à : %s",
    UNSCANNED       = "%d membre(s) pas encore analysé(s)",
    SET_GAINED      = "Bonus de set gagné : %d palier(s)",
    SET_LOST        = "Bonus de set perdu : %d palier(s)",
    SET_PARTIAL     = "Analyse partielle : paliers de set non lisibles",
    SET_UNVALUED    = "(non chiffré dans le verdict)",
    VERDICT_EQUIP   = "À ÉQUIPER",
    VERDICT_OFFSPEC = "OFF-SPÉ",
    VERDICT_SELL    = "VENDRE / DÉSENCHANTER",

    HELP = {
        "/fsb : ouvre la configuration",
        "/fsb on | off : active ou désactive l'analyse",
        "/fsb auto : profil automatique selon la spé",
        "/fsb spe : choisir sa spécialisation manuellement",
        "/fsb specprofil <profil> : associe un profil à la spé actuelle",
        "/fsb set [<valeur>] : valeur d'un palier de bonus de set (profil actif, 0 = non estimé)",
        "/fsb etat : diagnostic (mode, scan, spé)",
        "/fsb profils : liste les profils",
        "/fsb profil <nom> : choisit le profil actif",
        "/fsb nouveau <nom> : crée un profil (copie du profil actif)",
        "/fsb supprimer <nom> : supprime un profil",
        "/fsb poids [<stat> <valeur>] : affiche ou modifie les poids du profil actif",
        "/fsb sonde : vérifie les API en jeu (lecture seule)",
        "/fsb inconnus : stats rencontrées et non reconnues",
    },
    PROFILE_ACTIVE  = "Profil actif : %s",
    PROFILE_UNKNOWN = "Profil introuvable : %s",
    PROFILE_CREATED = "Profil créé : %s",
    PROFILE_EXISTS  = "Nom invalide ou déjà utilisé : %s",
    PROFILE_DELETED = "Profil supprimé : %s",
    PROFILE_KEEP_ONE = "Impossible de supprimer ce profil.",
    WEIGHT_SET      = "%s = %s (profil %s)",
    STAT_UNKNOWN    = "Stat inconnue : %s (alias : voir /fsb poids)",
    NO_UNKNOWN      = "Aucune stat inconnue rencontrée.",
    AUTO_ON         = "Profil automatique activé.",
    SET_VALUE       = "Valeur d'un palier de set : %s (profil %s)",
    SPEC_MAPPED     = "Spé actuelle associée au profil : %s",
    STATE           = "Mode : %s | membres à scanner : %d | membres comparables : %d",
    STATE_SPEC      = "Spé : %s | profil : %s (%s)",

    -- Interface
    UI_TITLE        = "Forever Stuff Book",
    UI_ENABLED      = "Analyse activée",
    UI_AUTO         = "Profil automatique (selon la spé)",
    UI_PROFILES     = "Profils",
    UI_NEW          = "Créer",
    UI_DELETE       = "Supprimer",
    UI_WEIGHTS      = "Poids des statistiques (profil actif)",
    UI_THRESHOLDS   = "Seuils (%)",
    UI_UPGRADE      = "Upgrade min.",
    UI_MARGIN       = "Marge « autre »",
    UI_SETVALUE     = "Valeur palier de set",
    UI_PICK_SPEC    = "Choisir ma spé",
    SPEC_PICK_TITLE = "Quelle est ta spécialisation ?",
    SPEC_AUTO       = "Auto (détection)",
}
